[package]
name = "galos_bot"
version = "0.0.0-dev+initial"
authors = ["Yev Krupetsky <yev.krupetsky@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
