runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        apt-get update -y
        apt-get install libczmq-dev -y

    - name: Checkout all submodules
      shell: bash
      run: git submodule update --init --recursive

