name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SQLX_OFFLINE: true

    steps:
    - name: Install dependencies
      run: sudo apt-get install libczmq-dev

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Checkout all submodules
      run: git submodule update --init --recursive

    - name: Cache build artifacts
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target

    - name: Run tests
      run: cargo test --all
